Neka single listing fix module name
AritDeveloperCircle/findyourpeople pull request #108
Opened 2023-05-24 02:00 UTC by istoga

## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other (please specify here: <type here>)
  
  
## Description of what this Pull Request does
Rename file for singleListing module

## Related Tickets & Documents
- Closes #107 
- Related Issues: (enter ticket numbers here)
  
## QA Instructions, Screenshots, Recordings
Bug fix only
  
## Added/updated tests?
- [ ] Yes
- [ ] Not Yet, and here is why: __explain here__
- [ ] I need help with tests
- [X] No, and here is why: no testing

2023-05-24 16:56 UTC, jjleigh requested changes
Only a small change request.

The description of the PR states that this is a name change but this PR seems to be doing more than just that. Can you updated the description to explain what is happening here and also add screenshots if applicable.

2023-05-24 16:56 UTC, jjleigh commented on src/pages/managerDashboard.js
> +export default managerDashboard
Add a final new line here.

2023-05-30 10:43 UTC, ibimina approved these changes
LGTM

2023-06-01 23:04 UTC, jjleigh approved these changes

2023-06-01 23:04 UTC, merged