added name to team members
AritDeveloperCircle/findyourpeople pull request #11
Opened 2023-04-04 17:04 UTC by TaylorDJones11

2023-04-05 13:53 UTC, annonymousauthority submitted a review, later dismissed
LGTM

2023-04-05 13:57 UTC, annonymousauthority requested changes

2023-04-05 14:02 UTC, annonymousauthority approved these changes
Nice! LG

2023-04-09 02:03 UTC, msarit requested changes

2023-04-09 02:03 UTC, msarit commented on wireframes/Add Community Page.png
Let's have these wireframe images merged as part of a separate pull request @TaylorDJones11 .
Take them out of this current PR.

These images are 🙌🏾 🙌🏾 🙌🏾

2023-04-11 00:52 UTC, msarit commented
@TaylorDJones11 Fix the conflicts Taylor then I will merge 🙏🏾

2023-04-11 07:56 UTC, TaylorDJones11 commented
I made the changes to repo

2023-04-11 18:05 UTC, msarit approved these changes

2023-04-11 18:05 UTC, merged