Taylor adding terms conditions
AritDeveloperCircle/findyourpeople pull request #137
Opened 2023-06-09 09:46 UTC by TaylorDJones11

## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Other: Adding Terms & Conditions
  
  
## Description of what this Pull Request does
- Adding Generated Terms & Conditions and Privacy Policy to the Signup Form
- Linking the policies back to the Signup Form

## Related Tickets & Documents
- Closes #136 

  
## QA Instructions, Screenshots, Recordings
![Privacy](https://github.com/AritDeveloperCircle/findyourpeople/assets/72883059/fcde3c28-1767-45d7-b553-b9dd91de6a5a)

  
## Added/updated tests?
- [ ] Yes
- [ ] Not Yet, and here is why: __explain here__
- [ ] I need help with tests
- [x] No, and here is why: None at this time

2023-06-09 10:00 UTC, annonymousauthority requested changes
Changes needed

2023-06-09 11:00 UTC, TaylorDJones11 commented on src/pages/termsAndConditions.js
Please check the updated changes @annonymousauthority

2023-06-09 11:10 UTC, annonymousauthority approved these changes
LG

2023-06-10 00:09 UTC, msarit approved these changes

2023-06-10 00:10 UTC, merged