Chibuzo-Neka manager form(css)
AritDeveloperCircle/findyourpeople pull request #148
Opened 2023-06-19 05:19 UTC by Domicaren1

## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other (please specify here: <type here>)
- [ ] 
![Screenshot 2023-06-19 061347](https://github.com/AritDeveloperCircle/findyourpeople/assets/89045426/8b0bdd00-7181-4cde-9756-616ea2a0b5b3)
![Screenshot 2023-06-19 061548](https://github.com/AritDeveloperCircle/findyourpeople/assets/89045426/c8226a59-bd47-48c9-a6af-007fa2aa0779)

  
  
## Description of what this Pull Request does
Styling of Neka's manager form

## Related Tickets & Documents
- Closes # (add the ticket number here, like #1)
- Related Issues: (enter ticket numbers here)
  
## QA Instructions, Screenshots, Recordings
(In this section, describe how to QA/review your PR. Feel free to use screenshots and/or short videos)
  
## Added/updated tests?
- [ ] Yes
- [ ] Not Yet, and here is why: __explain here__
- [ ] I need help with tests
- [ ] No, and here is why: __explain here__

2023-06-21 15:40 UTC, ibimina commented
@Domicaren1 we don't need the image upload

2023-06-22 23:02 UTC, Domicaren1 commented
> @Domicaren1 we don't need the image upload

ok

2023-06-23 22:56 UTC, ibimina commented
okay

2023-06-25 11:06 UTC, ibimina commented
@jjleigh @msarit  can we merge this

2023-06-25 16:11 UTC, annonymousauthority requested changes
Seen

2023-06-25 16:11 UTC, annonymousauthority commented on src/pages/helperFile.js
> +          const uploadpath = `thumbnails/community/3fF17YaSFLHgRgksgVU8/${file.name}`;
Why's this hard coded? `3fF17YaSFLHgRgksgVU8`

2023-06-26 17:24 UTC, closed without merging